title: Site Title
description: >

url: "http://yourdomain.com"
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
exclude: [node_modules, gulpfile.js, package.json]
gems:
  - octopress-autoprefixer